// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZG3fk-QOVc9YWR0m1lyGdLsAskBmvAE',
    appId: '1:870820419615:web:15268511516791f2711d2a',
    messagingSenderId: '870820419615',
    projectId: 'agriconnect-efa2b',
    authDomain: 'agriconnect-efa2b.firebaseapp.com',
    storageBucket: 'agriconnect-efa2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsF_Dfryoyba8SvEl8NHU7yNym3UEOApQ',
    appId: '1:870820419615:android:08388c85c4681067711d2a',
    messagingSenderId: '870820419615',
    projectId: 'agriconnect-efa2b',
    storageBucket: 'agriconnect-efa2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1fMrSDFBhh8nv8OML1I7Gy7ZQSVPyXMc',
    appId: '1:870820419615:ios:100fddf0d53811da711d2a',
    messagingSenderId: '870820419615',
    projectId: 'agriconnect-efa2b',
    storageBucket: 'agriconnect-efa2b.appspot.com',
    iosClientId: '870820419615-gqj8ou6frv44nore1efkhda8tis6qttg.apps.googleusercontent.com',
    iosBundleId: 'com.example.agribenin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1fMrSDFBhh8nv8OML1I7Gy7ZQSVPyXMc',
    appId: '1:870820419615:ios:4ed8fd6b01b53e4f711d2a',
    messagingSenderId: '870820419615',
    projectId: 'agriconnect-efa2b',
    storageBucket: 'agriconnect-efa2b.appspot.com',
    iosClientId: '870820419615-8u0jikkhbo8chv23u9h6a8h1p20vr20c.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriconnectAfricaMain.RunnerTests',
  );
}
